name: 'CI'
on:
  pull_request:
    paths-ignore: [ '**.md' ]
  push:
    paths-ignore: [ '**.md' ]
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  python-job:
    permissions: write-all
    runs-on: ubuntu-latest
    name: Build and Deploy Docker
    continue-on-error: false
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
            python-version: 3.11

      - name: Install requirements
        run: |
            pip install -r requirements.txt

      - name: Run tests
        run: |
            python -m pytest