name: 'CI'
on:
  pull_request:
    paths-ignore: [ '**.md' ]
  push:
    paths-ignore: [ '**.md' ]
    branches:
      - main
  workflow_dispatch:

permissions: 
  # Allows the EndBug/add-and-commit step to commit the package manager changes,
  # adding the AppMap language library and configuration file appmap.yml.
  # Once the EndBug/add-and-commit is removed, this permission can be removed, 
  # unless you need it for other reasons.
  contents: write

  # Allows the getappmap/archive-action to write a PR comment with the 
  # AppMap configuration status.
  pull-requests: write

jobs:
  python-job:
    permissions: write-all
    runs-on: ubuntu-latest
    name: Build and Deploy Docker
    continue-on-error: false
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
            python-version: 3.11

      - name: Install requirements
        run: |
            pip install -r requirements.txt

      - name: Run tests
        run: |
            python -m pytest
